### ISSUE TITLE
Add kubernetes to the dependencies

### ISSUE THREAD

**Issue by shqear93** [eslam-gomaa/kptop#38]
After installation, it doesn't work due to missing module 'kubernetes', should be added to the dependencies

```
Traceback (most recent call last):
  File "/Users/khaled-abushqear/Library/Python/3.11/bin/kptop", line 5, in <module>
    from kptop_tool import run
  File "/Users/khaled-abushqear/Library/Python/3.11/lib/python/site-packages/kptop_tool.py", line 6, in <module>
    run()
  File "/Users/khaled-abushqear/Library/Python/3.11/lib/python/site-packages/kptop_tool.py", line 3, in run
    from kubePtop.cli import Cli
  File "/Users/khaled-abushqear/Library/Python/3.11/lib/python/site-packages/kubePtop/cli.py", line 6, in <module>
    from kubePtop.session import PrometheusAPI
  File "/Users/khaled-abushqear/Library/Python/3.11/lib/python/site-packages/kubePtop/session.py", line 19, in <module>
    from kubernetes import config
ModuleNotFoundError: No module named 'kubernetes'

```

**Comment by eslam-gomaa** [comment]
done
